import type { SoundDefinition, SoundId } from "./types";

const AUDIO_ROOT = "/audio/sfx/v1";

export const AUDIO_MANIFEST: Record<SoundId, SoundDefinition> = {
  matchStart: {
    src: `${AUDIO_ROOT}/match-start.ogg`,
    volume: 0.72,
    cooldownMs: 1_000,
    maxVoices: 1,
    priority: 70,
  },
  turnSelf: {
    src: `${AUDIO_ROOT}/turn-self.ogg`,
    volume: 0.7,
    cooldownMs: 500,
    maxVoices: 1,
    priority: 55,
  },
  turnOpponent: {
    src: `${AUDIO_ROOT}/turn-opponent.ogg`,
    volume: 0.54,
    cooldownMs: 500,
    maxVoices: 1,
    priority: 50,
  },
  cardPlayCharacter: {
    src: `${AUDIO_ROOT}/card-play-character.ogg`,
    volume: 0.72,
    cooldownMs: 80,
    maxVoices: 2,
    priority: 35,
    pitchVariance: 0.025,
  },
  cardPlayEvent: {
    src: `${AUDIO_ROOT}/card-play-event.ogg`,
    volume: 0.76,
    cooldownMs: 80,
    maxVoices: 2,
    priority: 38,
    pitchVariance: 0.02,
  },
  cardPlayStage: {
    src: `${AUDIO_ROOT}/card-play-stage.ogg`,
    volume: 0.72,
    cooldownMs: 80,
    maxVoices: 2,
    priority: 36,
    pitchVariance: 0.02,
  },
  attachDon: {
    src: `${AUDIO_ROOT}/attach-don.ogg`,
    volume: 0.65,
    cooldownMs: 65,
    maxVoices: 2,
    priority: 32,
    pitchVariance: 0.035,
  },
  attack: {
    src: `${AUDIO_ROOT}/attack.ogg`,
    volume: 0.82,
    cooldownMs: 120,
    maxVoices: 2,
    priority: 60,
    pitchVariance: 0.02,
  },
  block: {
    src: `${AUDIO_ROOT}/block.ogg`,
    volume: 0.8,
    cooldownMs: 120,
    maxVoices: 2,
    priority: 62,
  },
  counter: {
    src: `${AUDIO_ROOT}/counter.ogg`,
    volume: 0.72,
    cooldownMs: 80,
    maxVoices: 2,
    priority: 52,
    pitchVariance: 0.025,
  },
  effect: {
    src: `${AUDIO_ROOT}/effect.ogg`,
    volume: 0.66,
    cooldownMs: 140,
    maxVoices: 2,
    priority: 42,
    pitchVariance: 0.02,
  },
  reveal: {
    src: `${AUDIO_ROOT}/reveal.ogg`,
    volume: 0.74,
    cooldownMs: 150,
    maxVoices: 2,
    priority: 46,
  },
  damage: {
    src: `${AUDIO_ROOT}/damage.ogg`,
    volume: 0.9,
    cooldownMs: 130,
    maxVoices: 2,
    priority: 78,
    pitchVariance: 0.025,
  },
  ko: {
    src: `${AUDIO_ROOT}/ko.ogg`,
    volume: 0.88,
    cooldownMs: 160,
    maxVoices: 2,
    priority: 80,
    pitchVariance: 0.02,
  },
  win: {
    src: `${AUDIO_ROOT}/win.ogg`,
    volume: 0.82,
    cooldownMs: 2_000,
    maxVoices: 1,
    priority: 100,
  },
  lose: {
    src: `${AUDIO_ROOT}/lose.ogg`,
    volume: 0.76,
    cooldownMs: 2_000,
    maxVoices: 1,
    priority: 100,
  },
  prompt: {
    src: `${AUDIO_ROOT}/prompt.ogg`,
    volume: 0.58,
    cooldownMs: 350,
    maxVoices: 1,
    priority: 58,
  },
  hexDraftOpen: {
    src: `${AUDIO_ROOT}/hex-draft-open.ogg`,
    volume: 0.68,
    cooldownMs: 800,
    maxVoices: 1,
    priority: 64,
  },
  hexDraftRefresh: {
    src: `${AUDIO_ROOT}/hex-draft-refresh.ogg`,
    volume: 0.66,
    cooldownMs: 250,
    maxVoices: 1,
    priority: 61,
  },
  hexDraftConfirm: {
    src: `${AUDIO_ROOT}/hex-draft-confirm.ogg`,
    volume: 0.74,
    cooldownMs: 500,
    maxVoices: 1,
    priority: 68,
  },
  error: {
    src: `${AUDIO_ROOT}/error.ogg`,
    volume: 0.62,
    cooldownMs: 300,
    maxVoices: 1,
    priority: 72,
  },
  disconnect: {
    src: `${AUDIO_ROOT}/disconnect.ogg`,
    volume: 0.62,
    cooldownMs: 1_000,
    maxVoices: 1,
    priority: 85,
  },
  reconnect: {
    src: `${AUDIO_ROOT}/reconnect.ogg`,
    volume: 0.58,
    cooldownMs: 1_000,
    maxVoices: 1,
    priority: 76,
  },
  message: {
    src: `${AUDIO_ROOT}/message.ogg`,
    volume: 0.52,
    cooldownMs: 300,
    maxVoices: 1,
    priority: 45,
  },
};

export const PRELOAD_SOUND_IDS = Object.keys(AUDIO_MANIFEST) as SoundId[];
